basePath: /gf/api
definitions:
  controller.ResponseMsg:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: process successfully
        type: string
    type: object
  controller.UserInfo:
    properties:
      ForAdmin:
        type: boolean
      NewPassword:
        example: 3ecb441b741bcd433288f5557e4b9118
        type: string
      Password:
        example: f9ae5f68ae1e7f7f3fc06053e9b9b539
        type: string
      Username:
        example: yingjiechen21
        type: string
    type: object
host: http://167.71.166.120:10010
info:
  contact: {}
  description: This is the Gator Forum Backend Server
  termsOfService: https://github.com/fongziyjun16/SE/tree/backend
  title: Gator Forum Backend API
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: only need strings username & password
      parameters:
      - description: only needs username and password
        in: body
        name: UserInfo
        required: true
        schema:
          $ref: '#/definitions/controller.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: <b>Success</b>. User Login Successfully
          schema:
            $ref: '#/definitions/controller.ResponseMsg'
        "400":
          description: <b>Failure</b>. Bad Parameters or Username / Password incorrect
          schema:
            $ref: '#/definitions/controller.ResponseMsg'
        "500":
          description: <b>Failure</b>. Server Internal Error.
          schema:
            $ref: '#/definitions/controller.ResponseMsg'
      summary: Admin / Regular User login
      tags:
      - User Manage
  /user/register:
    post:
      consumes:
      - application/json
      description: only need strings username & password
      parameters:
      - description: Regular User Register only needs Username, Password(encoded by
          md5) & ForAdmin with false.
        in: body
        name: UserInfo
        required: true
        schema:
          $ref: '#/definitions/controller.UserInfo'
      produces:
      - application/json
      responses:
        "201":
          description: <b>Success</b>. User Register Successfully
          schema:
            $ref: '#/definitions/controller.ResponseMsg'
        "400":
          description: <b>Failure</b>. Bad Parameters or User Has Existed
          schema:
            $ref: '#/definitions/controller.ResponseMsg'
        "500":
          description: <b>Failure</b>. Server Internal Error.
          schema:
            $ref: '#/definitions/controller.ResponseMsg'
      summary: Register a new Regular User
      tags:
      - User Manage
swagger: "2.0"
