# This yaml config file is a demo, so the value of each field is not real, but you can try

server:
  port: "Go Pikachu"

database:
  ip: "007.007.007.007"
  port: "6007"
  username: "Jame"
  password: "Bond"
  db1: "MI6"
  db2: "MI76"

redis:
  ip: "009.009.009.009"
  port: "6009"
  password: "rocket on!!!"
  db: 0

elasticsearch:
  ip: "009.009.009.009"
  port: "6009"
  username: "elastic"
  password: "es.js"

jwt:
  secretkey: "SpiderMan"
  expires: 100000

logger:
  # Debug < Info < Warn < Error
  lowestlevel: "Debug"
  path:
    debug: "./log/runtime/debug.log"
    info: "./log/runtime/info.log"
    warn: "./log/runtime/warn.log"
    error: "./log/runtime/error.log"