# This yaml config file is a demo, so the value of each field is not real, but you can try

server:
  port: "*****"

database:
  ip: "***.***.***.***"
  port: "3306"
  username: "scott"
  password: "superman"
  db1: "**"
  db2: "**"

redis:
  ip: "***.***.***.***"
  port: "6379"
  password: "rocket on!!!"
  db: 0

jwt:
  secretkey: "uf.edu"
  expires: 100000

logger:
  # Debug < Info < Warn < Error
  lowestlevel: "Debug"
  path:
    debug: "./log/runtime/debug.log"
    info: "./log/runtime/info.log"
    warn: "./log/runtime/warn.log"
    error: "./log/runtime/error.log"