# This yaml config file is a demo, so the value of each field is not real, but you can try

server:
  port: "*****"

database:
  ip: "***.***.***.***"
  port: "3306"
  username: "scott"
  password: "superman"
  db1: "**"
  db2: "**"

logger:
  # Debug < Info < Warn < Error
  lowest_level: "Debug"
  debug_path: "./log/runtime/debug.log"
  info_path: "./log/runtime/info.log"
  warn_path: "./log/runtime/warn.log"
  error_path: "./log/runtime/error.log"